version: '3.8'

services:
  app:
    build: .
    container_name: pyspark
    ports:
      - "8888:8888"  # Expose Jupyter Notebook
    volumes:
      - .:/home  # Mount current directory into /home in the container
    depends_on:
      - db  # Ensure the database starts before the app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"  # Expose PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
